const types = {
    FETCH_USER_AUTHENTICATION: "FETCH_USER_AUTHENTICATION",
    GET_USER_AUTHENTICATION: "GET_USER_AUTHENTICATION",
    ERROR_USER_AUTHENTICATION: "ERROR_USER_AUTHENTICATION",
    FETCH_PLANETS_DETAILS: "FETCH_PLANETS_DETAILS",
    GET_PLANETS_DETAILS: "GET_PLANETS_DETAILS",
    ERROR_PLANETS_DETAILS: "ERROR_PLANETS_DETAILS"
}

export default types;